main: community.leaf.examples.eventful.bukkit.ExampleEventfulPlugin
name: ${project.name}
version: ${revision}
api-version: 1.13

commands:
  test-events:
    aliases: [testevents]
    permission: events.test
